# SPDX-License-Identifier: BSD 3-Clause Revised
#
# author: Gregor A. Segner
---

# ensure additional bash functions are available on *nix systems
- name: ensure additional bash functions are present
  block:
    - ansible.builtin.file:
        path: '/usr/local/lib/bash'
        state: directory
        owner: root
        group: root
        mode: '0755'

    - ansible.builtin.get_url:
        url: 'https://raw.githubusercontent.com/g4s/collecction/master/nix/lib/{{ item }}'
        dest: '/usr/local/lib/bash/{{ item }}'
        owner: root
        group: root
        mode: '0755'
      loop:
        - 'system.sh'
  when: ansible_os_family != 'Windows'

- name: ensure hostname is set
  block:
    - ansible.builtin.hostname: {{ hostname | default('machine001') }}
      when: ansible_os_family != 'Windows'

- name: ensure system has latest pci-IDs
  ansible.builtin.command: 'update-pciids'
  when: ansible_os_family != 'Windows'

- ansible.builtin.include_tasks:
    file: './tasks/{{ ansible_os_family }}/main.yml'

- ansible.builtin.include_role:
    name: de.seafi.tailscale

- ansible.builtin.include_tasks:
    file: "./tasks/ntp.yml"