# macOS specific configurations
---

- ansible.builtin.include_file:
      name: "{{ ansible_os_family }}/time.yaml"

- ansible.builtin.inlcude_file:
      name: "{{ ansible_os_family }}/prequesites.yaml"

- ansible.builtin.include_file:
      name: "{{ ansible_os_family }}/updates.yaml"

- ansible.builtin.inlclude_file:
      name: "{{ absible_os_family}}/tools"

- name: ensure Amethyst window manager is present on system
  community.general.homebrew:
      name: "amethyst"
      state: latest

- name: ensure ShortCat keyboard enchancements are present on system
  community.general.homebrew:
      name: "shortcat"
      state: latest

- ansible.builtin.include_files:
      name: "{{ ansible_os_family }}/network.yaml"
