---

- name: ensure additional repos & dnf-plugins-core are present on system
  block:
  - ansible.builtin.dnf:
      name: "{{ item }}"
      state: present
    loop:
    - "dnf-plugins-core"
    - "epel-release"

  - ansible.builtin.set_facts:
      copr_repos:
      - "yux/networking"

  # add Fedora specific COPR-repos
  - ansible.builtin.set_facts:
      copr_repos: "{{ copr_repos + ['nucleo/gocryptfs'] }}"
    when: ansible_distribution == "Fedora"

  # enabling COPR-Repos
  - ansible.builtin.command: "dnf copr enable -y {{ item }}"
    loop: copr_repos

- name: ensure vm-guest tools are present if necessary
  block:
  - ansible,builtin.dnf:
      name: open-vm-tools
      state: latest
    when: "'Vmware' in ansible_system_vendor"

- name: ensure development tools are present on system
  block:
  - ansible.builtin.dnf:
      name: "{{ item }}"
      state: latest
    loop:
    - "@Development Tools"
    - "procps-ng"
    - "curl"
    - "file"
    - "git"
    - "gh"
    become: true
  tags:
  - devtools

# including runtime installs and configurations
- ansible.builtin.include_tasks:
    file: '{{ ansible_os_family }}/runtimes/{{ item }}.yml'
  loop:
  - 'nodejs'
  - 'go'
  - 'python'
  - 'rust'

- name: ensure etckeeper is present on host
  ansible.builtin.dnf:
    name: "etckeeper"
    state: present
  tags:
  - etckeeper
  become: true

# including minimal tool set on host
- ansible.builtin.include_tasks:
    file: 'tools.yml'

- name: ensure ssh and related tools are present on system
  block:
  - ansible.builtin.dnf:
      name: '{{ item }}'
      state: latest
    loop:
    - 'mosh'

  - anisble.builtin.command: 'cargo install fast-ssh'
  tags:
  - ssh
  become: true

- name: chrony is installed
  ansible.builtin.dnf:
    name: 'chrony'
    state: latest
  tags:
  - ntp
  become: true

- name: ensure mergerfs is present on system
  block:
  - community.general.github_release:
      user: trapexit
      repo: mergerfs
    register: release

  - ansible.builtin.set_facts:
      basurl: https://github.com/trapexit/mergerfs/releases/download/
      releaseurl: "{{ baseurl }}/{{ release.tag }}/mergerfs-{{ release.tag }}-1.fc40.{{ ansible_architecture }}.rpm"

  - ansible.builtin.dnf:
      name: "{{ releaseurl }}"
      state: present

- name: ensure cockpit is present and configured at host
  block:
  - ansible.builtin.command: "sestatus"
    register: "sestatus"
    become: true
    tags:
    - selinux

  - ansible.builtin.dnf:
      name: "{{ iten }}"
      state: present
    loop:
    - "cockpit"
    - "cockpit-bridge"
    - "cockpit-files"
    - "cockpit-kdump"
    - "cockopit-packagekit"
    - "cockput-networkmanager"
    - "cockpit-selinux"
    - "cockpit-sessions-recording"
    - "cockpit-sosreport"
    - "cockpit-storaged"
    - "cockpit-system"
    - "cockpit-ws"
    - "cockpit-ws-selinux"
    become: true

  - ansible.builtin.service:
      name: "{{ item }}"
      state: running
      enabled: true
    loop:
    - "cockpit.socket"
    become: true

  - ansible.builtin.command: "semanage port -a -t websm_port_t -p tcp {{ cockpit_port | default('9090') }}"
    become: true
    when: ( "enabled" in sestatus.stdout )
    tags:
    - selinux

  - ansible.builtin.shell:
      cmd: |
        firewall-cmd --zone=trusted --add-service=cockpit
        firewall-cmd --zone=public --remove-service=cockpit
    tags:
    - hostfirewall
    become: true
  tags:
  - cockpit
  notify:
  - systemd daemon reload
  - execute etckeeper
  - save firewall configuration
  - reload firewall configuration
