---

- name: aktivate epel
  block:
    - ansible.builtin.dnf:
        name: 'epel-release'
        state: present
  become: true

- name: enable yux/networking repo
  ansible.builtin.command: "dnf copr enable -y yux/networking"

# including runtime installs and configurations
- ansible.builtin.include_tasks:
    file: 'runtimes/{{ item }}.yml'
  loop:
    - 'nodejs'
    - 'go'
    - 'python'

# including minimal tool set on host
- ansible.builtin.include_tasks:
    file: 'tools.yml'

- name: chrony is installed
  ansible.builtin.dnf:
    name: 'chrony'
    state: latest
  tags:
    - ntp