---

- name: aktivate epel
  block:
    - ansible.builtin.dnf:
        name: 'epel-release'
        state: present
  become: true

- name: enable yum/networking repo
  ansible.builtin.command: "dnf copr enable -y yux/networking"

- name: ensure vm-guest tools are present if necessary
  block: 
    - ansible,builtin.dnf:
        name: open-vm-tools
        state: latest
      when: "'Vmware' in ansible_system_vendor"

# including runtime installs and configurations
- ansible.builtin.include_tasks:
    file: 'runtimes/{{ item }}.yml'
  loop:
    - 'nodejs'
    - 'go'
    - 'python'
    - 'rust'

# including minimal tool set on host
- ansible.builtin.include_tasks:
    file: 'tools.yml'

- name: chrony is installed
  ansible.builtin.dnf:
    name: 'chrony'
    state: latest
  tags:
    - ntp