# installing some essential tools on host.
---

- name: ensure {{ item }} is present on system
  ansible.builtin.dnf:
    name: '{{ item }}'
    state: latest
  loop:
    - 'tmux'
    - 'reptyr'
    - 'resty'
    - 'vim'
    - 'pv'
    - 'p7zip'
    - 'p7zip-plugins'
    - 'dmg2img'
    - 'wget'
    - 'ncdu'
    - 'lshw'
    - 'rclone'
    - 'age'
  become: true


- name: ensure flexihub is present o system
  block:
    - ansible.builtin.set_facts:
        flexispot_rpm: "https://cdn.electronic.us/products/flexihub/linux/download/flexihub.x86_64-2.rpm"

    - ansible.builtin.dnf:
        name: "{{ flexispot_rpm }}"
        state: present
  when: '"usbtools" in pckgs'


- name: ensure SEH UTN manager is present on system
  block:
    - ansible.builtin.set_facts:
        utnmanager_rpm: "https://www.seh-technology.com/fileadmin/user/downloads/deviceserver/tools/sehutnmanager-rpm_linux_64bit-4.0.7.zip"

    - ansible.builtin.dnf:
        name: "{{ utnmanager_rpm }}"
        state: present
  when: '"usbtools" in pckgs'